services:
  db:
    image: mysql:8.2.0
    container_name: mysql_prod
    ports:
      - "20001:3306"  # Puerto para MySQL en el rango permitido
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: a23adrestmar_tr2_g10
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer_prod
    depends_on:
      - db
    ports:
      - "20002:8080"  # Puerto para Adminer
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_prod
    volumes:
      - ./backend:/var/www/
    working_dir: /var/www/
    depends_on:
      - db
    command: bash -c "
      chmod +x entrypoint.sh && \
      ./entrypoint.sh && \
      composer install --no-dev --optimize-autoloader --no-interaction && \
      php artisan key:generate && \
      php artisan migrate --force && \
      php artisan config:cache && \
      php artisan route:cache && \
      php artisan view:cache"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_prod
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build"
    networks:
      - app_network

  nodejs:
    image: node:18
    container_name: nodejs_prod
    working_dir: /usr/src/app
    volumes:
      - ./backend/node-app:/usr/src/app
    command: bash -c "npm install && npm start"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - "20004:3000" 
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_prod
    depends_on:
      - backend
      - frontend
    ports:
      - "20003:80"  # Proxy inverso para Laravel y Vue
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge